### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by jeanpommier**
Builds against the studio v4

Basic config that assumes you might want to serve the static files with the same container as the API

Fixed and simplified the docker-compose.yml to match the default conf provided by https://github.com/mviewer/mviewerstudio/blob/master/config-python-sample.json

This is not a production composition, but aims at providing people with an insight of how it works and interconnects with mviewer, without complicating it with nginx proxy and such, and keeping the default config json file to simplify maintenance
(note: it might be better to use more standard path to mviewer, for instance /mviewer/ rather than http://127.0.0.1:5051/ as in the default conf. Would be more clear for newcomers too)

### CODE REVIEW

**Comment by jeanpommier** [comment]
I'm also stuffing the PROXY_WHITE_LIST related commit here, because it is very much relevant for docker environment. If you prefer, I can split it into a separate PR

**Comment by Gaetanbrl** [comment]
### PR STATUS - HIGHT-PRIORITY

`\0/`  Thanks a lot @jeanpommier for this PR / contribution !

> (note: it might be better to use more standard path to mviewer, for instance /mviewer/ rather than http://127.0.0.1:5051/ as in the default conf. Would be more clear for newcomers too)

Good point !

> If you prefer, I can split it into a separate PR

Not required 👍 

> This is not a production composition

Whats if some users need a prod composition with docker ? Just to know / inform.

> Fixed and simplified the docker-compose.yml

Just to be sur,  only one commands to execute docker compose ? (`docker compose docker-compose.yml`)

**Comment by jeanpommier** [comment]
> Whats if some users need a prod composition with docker ? Just to know / inform.

I could configure it easily, but I'd like to keep using the sample config file as it is, in order to avoid what we had previously, a separate config file, that was actually completely outdated. I will give it some thought

**Comment by jeanpommier** [comment]
> Just to be sur, only one commands to execute docker compose ? (`docker compose docker-compose.yml`)

`docker compose` is enough since the yaml file has the default name

**Pull request merged**
